<?php
/**
 * Sela Hero — render template.
 *
 * Available variables (injected by Hero_Section_Renderer):
 *   @var array  $settings  Merged field values.
 *   @var array  $blocks    Prepared block instances (unused for hero).
 *   @var array  $section   [ 'id' => string, 'type' => string, 'source' => string ]
 */

defined( 'ABSPATH' ) || exit;

// ── Content
$title    = (string) ( $settings['title']    ?? 'Cloud services and AI solutions for startups & SaaS companies' );
$subtitle = (string) ( $settings['subtitle'] ?? 'As a top-tier partner of AWS, Microsoft Azure, and Google Cloud, Sela optimizes cloud spend, accelerates development, and boosts growth.' );
$cta_text = (string) ( $settings['cta_text'] ?? 'Get Started' );
$cta_link = (string) ( $settings['cta_link'] ?? '#' );

// title_tag / subtitle_tag are auto-generated by Hero_Section_Registry.
$title_tag    = function_exists( 'hero_pick_tag' )
    ? hero_pick_tag( (string) ( $settings['title_tag']    ?? 'auto' ), 'h1' )
    : 'h1';
$subtitle_tag = function_exists( 'hero_pick_tag' )
    ? hero_pick_tag( (string) ( $settings['subtitle_tag'] ?? 'auto' ), 'p' )
    : 'p';

// ── Typography
$ff_title   = (string) ( $settings['ff_title']   ?? "'Lexend', sans-serif" );
$fz_title_d = (int)    ( $settings['fz_title_d'] ?? 52 );
$fz_title_m = (int)    ( $settings['fz_title_m'] ?? 30 );
$fw_title   = (string) ( $settings['fw_title']   ?? '300' );
$lh_title   = ( (int)   ( $settings['lh_title']  ?? 111 ) ) / 100;
$ls_title   = (float)  ( $settings['ls_title']   ?? 0 );

$ff_sub   = (string) ( $settings['ff_sub']   ?? "'Lexend', sans-serif" );
$fz_sub_d = (int)    ( $settings['fz_sub_d'] ?? 16 );
$fz_sub_m = (int)    ( $settings['fz_sub_m'] ?? 14 );
$fw_sub   = (string) ( $settings['fw_sub']   ?? '300' );
$lh_sub   = ( (int)   ( $settings['lh_sub']  ?? 158 ) ) / 100;

// ── Colors
$bg_section  = (string) ( $settings['bg_section']  ?? '#f9f9f9' );
$color_title = (string) ( $settings['color_title'] ?? '#1c1c1c' );
$color_sub   = (string) ( $settings['color_sub']   ?? '#585858' );
$color_btn   = (string) ( $settings['color_btn']   ?? '#1c1c1c' );

$orb_cyan_c  = (string) ( $settings['orb_cyan_color']  ?? '#00dbe9' );
$orb_green_c = (string) ( $settings['orb_green_color'] ?? '#00dd95' );
$orb_blue_c  = (string) ( $settings['orb_blue_color']  ?? '#0071f6' );
$orb_pink_c  = (string) ( $settings['orb_pink_color']  ?? '#f191a1' );

// ── Visibility
$show_orb_cyan  = ! empty( $settings['show_orb_cyan'] );
$show_orb_green = ! empty( $settings['show_orb_green'] );
$show_orb_blue  = ! empty( $settings['show_orb_blue'] );
$show_orb_pink  = ! empty( $settings['show_orb_pink'] );
$show_robot     = ! empty( $settings['show_robot'] );
$show_stars     = ! empty( $settings['show_stars'] );
$show_clouds    = ! empty( $settings['show_clouds'] );

// ── Media base (uploads-sourced sections live under wp-content/uploads/hero/sections/<slug>/media/)
$media_base = '';
$source     = (string) ( $section['source'] ?? '' );
$type       = (string) ( $section['type']   ?? 'sela-hero' );
if ( $source === 'uploads' ) {
    $u = wp_upload_dir();
    $media_base = trailingslashit( $u['baseurl'] ) . 'hero/sections/' . sanitize_key( $type ) . '/media/';
} else {
    // For plugin/theme sources, the registry already converted defaults to absolute URLs.
    // Leave $media_base empty so $get_img returns whatever the field has.
}

// Image helper — prefer admin-set URL, otherwise fall back to bundled file.
$get_img = function ( string $key, string $fallback ) use ( $settings, $media_base ): string {
    $val = (string) ( $settings[ $key ] ?? '' );
    if ( $val !== '' ) {
        return esc_url( $val );
    }
    if ( $media_base !== '' ) {
        return esc_url( $media_base . ltrim( $fallback, '/' ) );
    }
    return '';
};

// Unique per-instance ID for scoping the inline <style> block.
$uid = 'slhe-' . esc_attr( $section['id'] ?? uniqid( 'sec', true ) );
?>
<style>
#<?php echo $uid; ?> {
    --slhe-bg:           <?php echo esc_attr( $bg_section ); ?>;
    --slhe-color-title:  <?php echo esc_attr( $color_title ); ?>;
    --slhe-color-sub:    <?php echo esc_attr( $color_sub ); ?>;
    --slhe-color-btn:    <?php echo esc_attr( $color_btn ); ?>;

    --slhe-ff-title: <?php echo $ff_title; ?>;
    --slhe-fz-title: <?php echo $fz_title_d; ?>px;
    --slhe-fw-title: <?php echo esc_attr( $fw_title ); ?>;
    --slhe-lh-title: <?php echo $lh_title; ?>;
    --slhe-ls-title: <?php echo $ls_title; ?>px;

    --slhe-ff-sub: <?php echo $ff_sub; ?>;
    --slhe-fz-sub: <?php echo $fz_sub_d; ?>px;
    --slhe-fw-sub: <?php echo esc_attr( $fw_sub ); ?>;
    --slhe-lh-sub: <?php echo $lh_sub; ?>;

    --slhe-orb-cyan:  <?php echo esc_attr( $orb_cyan_c ); ?>;
    --slhe-orb-green: <?php echo esc_attr( $orb_green_c ); ?>;
    --slhe-orb-blue:  <?php echo esc_attr( $orb_blue_c ); ?>;
    --slhe-orb-pink:  <?php echo esc_attr( $orb_pink_c ); ?>;
}
@media (max-width: 768px) {
    #<?php echo $uid; ?> {
        --slhe-fz-title: <?php echo $fz_title_m; ?>px;
        --slhe-fz-sub:   <?php echo $fz_sub_m; ?>px;
    }
}
</style>

<section class="slhe-section" id="<?php echo $uid; ?>">
    <div class="slhe-inline">

        <?php if ( $show_orb_cyan ) : ?>
            <div class="slhe-orb slhe-orb--cyan">
                <?php if ( $show_stars ) : ?>
                    <img class="slhe-star slhe-star--r" src="<?php echo $get_img( 'image_star', 'star.gif' ); ?>" alt="">
                <?php endif; ?>
                <div class="slhe-orb-shape" style="background:linear-gradient(179.86deg,rgba(0,219,233,0) 36%,var(--slhe-orb-cyan) 98%)"></div>
                <img class="slhe-orb-ellipse" src="<?php echo $get_img( 'image_orb_cyan', 'ellipse-cyan.svg' ); ?>" alt="">
            </div>
        <?php endif; ?>

        <?php if ( $show_orb_green ) : ?>
            <div class="slhe-orb slhe-orb--green">
                <div class="slhe-orb-shape" style="background:linear-gradient(179.86deg,rgba(0,221,149,0) 36%,var(--slhe-orb-green) 100%)"></div>
                <img class="slhe-orb-ellipse" src="<?php echo $get_img( 'image_orb_green', 'ellipse-green.svg' ); ?>" alt="">
            </div>
        <?php endif; ?>

        <?php if ( $show_orb_blue ) : ?>
            <div class="slhe-orb slhe-orb--blue">
                <div class="slhe-orb-shape" style="background:linear-gradient(179.18deg,rgba(0,113,246,0) 33%,var(--slhe-orb-blue) 100%)"></div>
                <img class="slhe-orb-ellipse" src="<?php echo $get_img( 'image_orb_blue', 'ellipse-blue.svg' ); ?>" alt="">
            </div>
        <?php endif; ?>

        <?php if ( $show_orb_pink ) : ?>
            <div class="slhe-orb slhe-orb--pink">
                <div class="slhe-orb-shape" style="background:linear-gradient(179.18deg,rgba(241,145,161,0) 33%,var(--slhe-orb-pink) 100%)"></div>
                <img class="slhe-orb-ellipse" src="<?php echo $get_img( 'image_orb_pink', 'ellipse-pink.svg' ); ?>" alt="">
            </div>
        <?php endif; ?>

        <?php if ( $show_clouds ) : ?>
            <img class="slhe-cloud slhe-cloud--1" src="<?php echo $get_img( 'image_cloud_1', 'cloud-hero-1.svg' ); ?>" alt="" aria-hidden="true">
            <img class="slhe-cloud slhe-cloud--2" src="<?php echo $get_img( 'image_cloud_2', 'cloud-hero-2.svg' ); ?>" alt="" aria-hidden="true">
            <img class="slhe-cloud slhe-cloud--3" src="<?php echo $get_img( 'image_cloud_3', 'cloud-hero-1.svg' ); ?>" alt="" aria-hidden="true">
            <img class="slhe-cloud slhe-cloud--4" src="<?php echo $get_img( 'image_cloud_4', 'cloud-hero-2.svg' ); ?>" alt="" aria-hidden="true">
            <img class="slhe-cloud slhe-cloud--6" src="<?php echo $get_img( 'image_cloud_6', 'cloud-hero-2.svg' ); ?>" alt="" aria-hidden="true">
        <?php endif; ?>

        <?php if ( $show_stars ) : ?>
            <img class="slhe-star slhe-star--l" src="<?php echo $get_img( 'image_star', 'star.gif' ); ?>" alt="">
            <img class="slhe-star slhe-star--r" src="<?php echo $get_img( 'image_star', 'star.gif' ); ?>" alt="">
        <?php endif; ?>

        <div class="slhe-content">
            <<?php echo $title_tag; ?> class="slhe-title"><?php echo wp_kses_post( $title ); ?></<?php echo $title_tag; ?>>
            <<?php echo $subtitle_tag; ?> class="slhe-sub"><?php echo wp_kses_post( $subtitle ); ?></<?php echo $subtitle_tag; ?>>
            <a href="<?php echo esc_url( $cta_link ); ?>" class="slhe-btn">
                <?php echo esc_html( $cta_text ); ?>
                <svg class="slhe-arrow" xmlns="http://www.w3.org/2000/svg" width="18.887" height="17.089" viewBox="0 0 20 18" fill="none">
                    <path d="M11.6795 14.4546L18.3049 8.62664L11.8943 2.66199" stroke="currentColor"/>
                    <path d="M0 8.62659L18.1001 8.62659" stroke="currentColor"/>
                </svg>
            </a>
        </div>

        <?php if ( $show_robot ) : ?>
            <div class="slhe-robot" aria-hidden="true">
                <img src="<?php echo $get_img( 'image_robot', 'hero-graphic.png' ); ?>" alt="">
            </div>
        <?php endif; ?>

    </div>

    <?php if ( $show_clouds ) : ?>
        <img class="slhe-cloud slhe-cloud--5" src="<?php echo $get_img( 'image_cloud_5', 'cloud-hero-1.svg' ); ?>" alt="" aria-hidden="true">
    <?php endif; ?>
</section>
