<?php
defined( 'ABSPATH' ) || exit;

return array(
    'type'     => 'sela-hero-lottie',
    'label'    => 'Sela Hero — Lottie',
    'category' => 'hero',
    'contexts' => array(
        'page',
    ),
    'settings' => array(
        array(
            'id'      => 'title',
            'type'    => 'textarea',
            'label'   => 'Title',
            'default' => 'Cloud services and AI solutions for startups & SaaS companies',
        ),
        array(
            'id'      => 'subtitle',
            'type'    => 'textarea',
            'label'   => 'Subtitle',
            'default' => 'As a top-tier partner of AWS, Microsoft Azure, and Google Cloud, Sela optimizes cloud spend, accelerates development, and boosts growth.',
        ),
        array(
            'id'      => 'cta_text',
            'type'    => 'text',
            'label'   => 'CTA text',
            'default' => 'Get Started',
        ),
        array(
            'id'      => 'cta_link',
            'type'    => 'url',
            'label'   => 'CTA link',
            'default' => '#',
        ),
        array(
            'id'      => 'lottie_desktop',
            'type'    => 'url',
            'label'   => 'Lottie background — desktop (JSON URL)',
            'default' => 'https://selacloud.ussl.co/wp-content/uploads/hero/sections/sela-hero-lottie/media/lottie-desktop.json',
        ),
        array(
            'id'      => 'lottie_mobile',
            'type'    => 'url',
            'label'   => 'Lottie background — mobile (JSON URL)',
            'default' => 'https://selacloud.ussl.co/wp-content/uploads/hero/sections/sela-hero-lottie/media/lottie-mobile.json',
        ),
        array(
            'tab'     => 'style',
            'id'      => 'ff_title',
            'type'    => 'select',
            'label'   => 'Title font',
            'default' => '\'Lexend\', sans-serif',
            'options' => array(
                array( 'value' => '\'Lexend\', sans-serif', 'label' => 'Lexend' ),
                array( 'value' => '\'Inter\', sans-serif', 'label' => 'Inter' ),
                array( 'value' => '\'Roboto\', sans-serif', 'label' => 'Roboto' ),
                array( 'value' => '\'Open Sans\', sans-serif', 'label' => 'Open Sans' ),
                array( 'value' => '\'Poppins\', sans-serif', 'label' => 'Poppins' ),
                array( 'value' => 'system-ui, sans-serif', 'label' => 'System UI' ),
            ),
        ),
        array(
            'tab'     => 'style',
            'id'      => 'fz_title_d',
            'type'    => 'range',
            'label'   => 'Title size — desktop (px)',
            'default' => 52,
            'min'     => 16,
            'max'     => 120,
            'step'    => 1,
        ),
        array(
            'tab'     => 'style',
            'id'      => 'fz_title_m',
            'type'    => 'range',
            'label'   => 'Title size — mobile (px)',
            'default' => 30,
            'min'     => 14,
            'max'     => 80,
            'step'    => 1,
        ),
        array(
            'tab'     => 'style',
            'id'      => 'fw_title',
            'type'    => 'select',
            'label'   => 'Title weight',
            'default' => '300',
            'options' => array(
                array( 'value' => '200', 'label' => 'Extra Light' ),
                array( 'value' => '300', 'label' => 'Light' ),
                array( 'value' => '400', 'label' => 'Regular' ),
                array( 'value' => '500', 'label' => 'Medium' ),
                array( 'value' => '600', 'label' => 'Semi Bold' ),
                array( 'value' => '700', 'label' => 'Bold' ),
            ),
        ),
        array(
            'tab'     => 'style',
            'id'      => 'lh_title',
            'type'    => 'range',
            'label'   => 'Title line-height (×100)',
            'default' => 111,
            'min'     => 80,
            'max'     => 250,
            'step'    => 1,
        ),
        array(
            'tab'     => 'style',
            'id'      => 'ls_title',
            'type'    => 'range',
            'label'   => 'Title letter-spacing (px)',
            'default' => 0,
            'min'     => -3,
            'max'     => 5,
            'step'    => 1,
        ),
        array(
            'tab'     => 'style',
            'id'      => 'ff_sub',
            'type'    => 'select',
            'label'   => 'Subtitle font',
            'default' => '\'Lexend\', sans-serif',
            'options' => array(
                array( 'value' => '\'Lexend\', sans-serif', 'label' => 'Lexend' ),
                array( 'value' => '\'Inter\', sans-serif', 'label' => 'Inter' ),
                array( 'value' => '\'Roboto\', sans-serif', 'label' => 'Roboto' ),
                array( 'value' => '\'Open Sans\', sans-serif', 'label' => 'Open Sans' ),
                array( 'value' => '\'Poppins\', sans-serif', 'label' => 'Poppins' ),
                array( 'value' => 'system-ui, sans-serif', 'label' => 'System UI' ),
            ),
        ),
        array(
            'tab'     => 'style',
            'id'      => 'fz_sub_d',
            'type'    => 'range',
            'label'   => 'Subtitle size — desktop (px)',
            'default' => 16,
            'min'     => 12,
            'max'     => 32,
            'step'    => 1,
        ),
        array(
            'tab'     => 'style',
            'id'      => 'fz_sub_m',
            'type'    => 'range',
            'label'   => 'Subtitle size — mobile (px)',
            'default' => 14,
            'min'     => 12,
            'max'     => 24,
            'step'    => 1,
        ),
        array(
            'tab'     => 'style',
            'id'      => 'fw_sub',
            'type'    => 'select',
            'label'   => 'Subtitle weight',
            'default' => '300',
            'options' => array(
                array( 'value' => '200', 'label' => 'Extra Light' ),
                array( 'value' => '300', 'label' => 'Light' ),
                array( 'value' => '400', 'label' => 'Regular' ),
                array( 'value' => '500', 'label' => 'Medium' ),
                array( 'value' => '600', 'label' => 'Semi Bold' ),
                array( 'value' => '700', 'label' => 'Bold' ),
            ),
        ),
        array(
            'tab'     => 'style',
            'id'      => 'lh_sub',
            'type'    => 'range',
            'label'   => 'Subtitle line-height (×100)',
            'default' => 158,
            'min'     => 80,
            'max'     => 250,
            'step'    => 1,
        ),
        array(
            'tab'     => 'style',
            'id'      => 'bg_section',
            'type'    => 'color',
            'label'   => 'Section background (fallback)',
            'default' => '#f9f9f9',
        ),
        array(
            'tab'     => 'style',
            'id'      => 'color_title',
            'type'    => 'color',
            'label'   => 'Title color',
            'default' => '#1c1c1c',
        ),
        array(
            'tab'     => 'style',
            'id'      => 'color_sub',
            'type'    => 'color',
            'label'   => 'Subtitle color',
            'default' => '#585858',
        ),
        array(
            'tab'     => 'style',
            'id'      => 'color_btn',
            'type'    => 'color',
            'label'   => 'Button color',
            'default' => '#1c1c1c',
        ),
    ),
    'blocks'   => array(
        'allowed' => array(),
        'max'     => 0,
    ),
);
